### ISSUE TITLE
Uvoz in poročilo

### ISSUE THREAD

**Issue by jaanos** [PezdirM14/APPR-2015-16#2]
Uvoz ti ne deluje, saj imaš zamenjani dve vrstici pri uvozu razpredelnice `Bmw_prodaja` - nanjo se sklicuješ, preden jo definiraš.

Da ti v poročilo ne bo izpisovalo obvestil ob uvozu knjižnic, vse klice ukaza `library` premakni iz `uvoz/uvoz.r` v `lib/libraries.r`. Druga možnost bi bila, da pri bloku, kjer kličeš `uvoz.r`, nastaviš `results='hide'` in `message=FALSE`, da se ta obvestila ne izpisujejo. Seveda dodaj v poročilo še kakšen graf.

**Comment by PezdirM14** [comment]
Hvala za opozorilo. Klice paketov sem premaknil, vendar če zaženem npr. knit word mi ukaze tipa "## Warning: package 'knitr' was built under R version 3.2.3" še vedno izpiše. Mogoče veste razlog za to? Poleg tega mi vse grafe nariše na začetku poročila in še enkrat vmes, kjer sem klical graf četudi sem v ukaz vstavil "results='hide',message=FALSE". Še en problem imam in sicer, ko delam sezname v rmarkdownu mi \* (neostevilčen seznam) ne naredi nič, mogoče veste zakaj? Mogoče je razlog v tem, da na računalniku nimam latexa in zaradi tega ne morem uporabljati "knit pdf". Hvala

**Comment by PezdirM14** [comment]
_Update_ 
Ugotovil sem, da mi je grafe v poročilu prikazovalo zato, ker sem imel v uvoz/uvoz.r  ukaz print(graf), kateri se je sprožil v poročilu. Torej ta napaka je odpravljena.

**Comment by jaanos** [comment]
Da ne bo izpisovalo opozoril, bloku kode, kjer uvoziš `libraries.r`, dodaj še parameter `warning=FALSE`. LaTeX si pa le namesti, da boš lahko točno videl, kako bo izgledalo poročilo.

Grafe ti riše na začetku poročila, ker imaš v `uvoz.r` ukaze `print`. Te odstrani, potem pa grafe izpisuj v poročilu.

Kar se tiče seznamov, pa moraš pred seznamom in za njim pustiti prazno vrstico, za začetno zvezdico (ali minusom) pa presledek. Podobno mora pred tremi zvezdicami in za njimi biti prazna vrstica, da se izriše vodoravna črta.

**Comment by PezdirM14** [comment]
Hvala za pomoč.

**Comment by PezdirM14** [comment]
Zdravo, imam še dve vprašanji, ki morda nista tako pomembni in če ste preveč zasedeni ni potrebno odgovoriti. Pri poročilu v rmarkdownu me zanima kako bi naslov grafa bil postavljen lepo na sredini(sedaj je zamaknjen) in kako bi v grafu na osi namesto dolgih imen mesecev zapisal kratke. Verjetno bi moral spremeniti "levels" v faktorju Mazda_prodaja$Mesec <- factor(Mazda_prodaja$Mesec, levels =
 Mazda_prodaja$Mesec, ordered = TRUE) v vektor z okrajšanimi imeni, vendar mi to ne deluje.

**Comment by PezdirM14** [comment]
_Update_
Oznake na x osi sem uspel zapisati navpično tako, da se ne prekrivajo več.

**Comment by PezdirM14** [comment]
Prosim, če posodobite predstavitev tudi meni. Hvala

**Comment by jaanos** [comment]
V redu, bom posodobil.

**Comment by jaanos** [comment]
Naslove grafov ti zamakne, ker imaš dejansko v nizu presledke po novi vrstici. Če hočeš določiti prelom, to narediš z `"\n"`, na primer

``` R
         skupni_graf<-ggplot(Prodaja, aes(x=Mesec, y=Povprečno, group=Proizvajalec, color =
                               Proizvajalec)) + geom_line() +
                               ggtitle("Povprečna prodaja avtomobilov po\nznamkah(2012-2015) v Europi po mesecih v tisočih")+
                               theme(plot.title = element_text(lineheight=.8, face="bold"),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

**Comment by PezdirM14** [comment]
Hvala, želel bi da posodobite še poročilo prosim
