### ISSUE TITLE
Prilagajanje

### ISSUE THREAD

**Issue by PezdirM14** [PezdirM14/APPR-2015-16#3]
Pozdravljeni, 
rad bi primerjal stolpca v tabeli tabela_EU_registracije_avtomobili in sicer stolpca vozaci in stevilo registracij, da bi lahko primerjal, če sta ti spremenljivki v kakšnem odnosu. Ko poskušam to storiti, tako kot smo storili na vajah, pri UScrime mi javlja napako da sta stolpca class character, ko pa to preverim sta oba stolpca class numeric. Zanima me, kako bi to težavo odpravil in naredil to za določeno državo ali kako bi bilo smiselno narediti prilagajanje, za posamezno državo ali za vse države? 
Lp in hvala vnaprej, Martin

**Comment by jaanos** [comment]
Najprej bi te opozoril, da ti `uvoz.r` ne deluje, saj se sklicuješ na `tabela_EU_vozaci`, preden to razpredelnico sploh uvoziš. Poleg tega pri pretvorbi stolpca `Stevilo vozacev` v števila pride do opozorila, saj imaš ponekod decimalne vejice - tam dobiš `NA`. Da se to ne bo zgodilo, pred pretvorbo v števila zamenjaj vejico s piko:

``` R
tabela_EU_vozaci$`Stevilo vozacev` <- tabela_EU_vozaci$`Stevilo vozacev` %>%
           {gsub("\\.", "", .)} %>% {gsub(",", ".", .)} %>% as.numeric()
```

Prav tako se v `vizualizacija.r` sklicuješ na spremenljivko `pred_krizo`, ki je nimaš nikjer definirane - najbrž hočeš tam imeti `izbrano_leto`, ustrezni stolpec pa je potem `Stevilo_registracij` (s podčrtajem).

Napako ti javi pri grafu `povezava`, saj si za podatke podal niz. Da ti ne bo izpisovalo opozorila o manjkajočih podatkih, lahko pri `geom_smooth` dodaš še parameter `na.rm = TRUE`:

``` R
povezava<-ggplot(tabela_EU_registracije_avtomobili,
                 aes(x=Stevilo_registracij, y=vozaci)) +
  geom_point(na.rm = TRUE) + geom_smooth(method="lm", na.rm = TRUE)
```

**Comment by PezdirM14** [comment]
Hvala in se opravičujem za pozen odgovor
